-- =======================================
-- DOMAINS
-- =======================================

CREATE DOMAIN PHONE_DOM AS VARCHAR(80);
CREATE DOMAIN EMAIL_DOM AS VARCHAR(1020);
CREATE DOMAIN ORDER_STATUS_DOM AS VARCHAR(80);

-- =======================================
-- TABLES
-- =======================================

-- TABLES
CREATE TABLE CUSTOMERS (
    ID INTEGER,
    NAME VARCHAR(400),
    EMAIL VARCHAR(1020),
    PHONE VARCHAR(80),
    CREATED_AT TIMESTAMP
);

CREATE TABLE PRODUCTS (
    ID INTEGER,
    NAME VARCHAR(600),
    SKU VARCHAR(200),
    PRICE BIGINT
);

CREATE TABLE ORDERS (
    ID INTEGER,
    CUSTOMER_ID INTEGER,
    ORDER_DATE DATE,
    STATUS VARCHAR(80),
    TOTAL_AMOUNT BIGINT
);

CREATE TABLE ORDER_ITEMS (
    ID INTEGER,
    ORDER_ID INTEGER,
    PRODUCT_ID INTEGER,
    QUANTITY INTEGER,
    UNIT_PRICE BIGINT
);




-- =======================================
-- PROCEDURES
-- =======================================

-- PROCEDURES
CREATE OR ALTER PROCEDURE SIMPLE_MAINTENANCE
AS
BEGIN
    /* TODO */
END;

CREATE OR ALTER PROCEDURE RECALC_STATS
AS
BEGIN
    /* TODO */
END;



